### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by hnw** [hnw/cloudpubsub-local-exec-subscriber#2]
- [ ] プロセスのタイムアウト時間を設定できるようにする
- [ ] プロセスキューを作って指定した並列数で実行できるようにする
- [ ] configを別ファイルに分ける
- [ ] `os.Exec` のテストを書く
- [ ] AWS対応（SNS+SQS？）
- [ ] 実行コマンドの指定 `[]strings` にする
- [ ] JSON変数を環境変数に展開する（本当に要る？）
